### ISSUE TITLE
A test issue

### ISSUE THREAD

**Issue by aolko** [aolko/xtruct#3]
This issue was created by [Maintainers Wanted](https://maintainerswanted.com)

**Comment by flxwu** [comment]
Hey @aolko ! Cool to see that you are using Maintainers Wanted! 😊 At the time that you registered your project, we haven't put in some proper text for the issue yet, as you can see here :) 

Would you mind joining us as beta-tester? It'd be cool if you'd close the issue (the Database Entry and the Webhook should be deleted then) and re-register your project on the website, as we have now put in some proper text for the issue! :)

Best,
Felix
